= Why Someday?

== Camping Log

November 11, 2022::
* Had 5th Wheel Installed on 2018 Ford F-150 at Ketelsen RV in Hiawath Iowa
* Bought 2022 Grand Design Reflection 295RL from Ketelsen RV in Hiawath Iowa

November 16, 2022::
* Took camper home to park in driveway
* Bumped back window with nose of camper and blew out back window!
* Got camper into the driveway and got truck wrapped with crash wrap
* Located new window at Ford of Murfreesboro, TN and booked a night at the Nashvill, I24 RV Park
* Scheduled glass install to be done at the campground

November 18, 2022::
* Hit the road with snow on the ground
* Truck did a good job pulling the camper
* First overnight at Harvest Host McDingerz Sports Bar & Grill in Eolia, MO
** Found that our batteries were near dead and we had no hookups at this host (known ahead of time but not fully understood)
** Ran to Lowe's and Home Depot to find a generator. Had to take what they had
** Ran generator all night
** Found it to be too big for the back of our truck while the camper was hitched so had to go and return it to Home Depot.
** Ordered a smaller and quiter one online from Home Depot to be delivered in Birmingham, AL
*** Champion Power Equipment - 4650-Watt Electric Start Portable Inverter Generator
** Realized too late that I had ordered the single fuel version instead of the dual fuel version
*** Ordered dual fuel version but goofed and had it shipped to store in our home town back in Iowa

NOTE: So at this point we had purchased 3 generators only to need to return them all for refunds

November 19, 2022::
* Stronger winds (12-15 MPG) with a SW wind coming at us as we headed South towards Memphis
* Found those winds to produce a tail wagging the dog feeling with the camper and truck
* Arrived at Big Buck Resort in Hornsby, TN after harrowing drive down a winding back road
** Made note to explore dedicated RV GPS systems

November 21, 2022::
* Worked in Jackson, TN

November 22, 2022::
* Arrived at Nashville I24 Campground in Smyrna, TN
* Picked up new back window glass at Ford of Murfreesboro
* Curiously looked at dually trucks there and also at Chevrolet Buick GMC of Murfreesboro
* Ordered Garmin - RVcam 795 7" GPS with Built-In Camera from Best Buy for store pickup in Trussville, AL

November 23, 2022::
* Had window installed by Hamilton Glass Company out of Murfreesboro, TN
* Hills as we approached Chattanooga got me quite nervous with the truck
** I felt like I was on the edge of being able to control the rig
* Arrived at Shellmound Campground in Jasper, TN
* Drove to Riverside Chevrolet Buick GMC in South Pittsburg, TN
** Bought a 2023 GMC 3500HD Denali Dually
** Left it at dealer overnight

November 24, 2022::
* Picked up the Denali and Melissa followed me back to the campground in the Ford
* Drove to Chattanooga to explore downtown, North Side, and drove up to Lookout Mountain in the Denali

November 25, 2022::
* Contacted Home Depot through their online chat and got order to Iowa cancelled
* Placed a new order for the dual fuel generator to be shipped to Daphne, AL

November 28, 2022::
* Picked up Garmin RVCam 

November 30, 2022::
* Major storm with flash flood and tornado concerns last night
** Camper felt solid but the storm was loud
** We lost power sometime in the middle of the night and I didn't get much sleep
** Power came back on by 8 am
* Storm brought cold with it and so we filled fresh water tank and disconnected the line
* Shot an intro video for the YouTube channel

December 1, 2022::
* Chilly morning just above freezing
* Shot first "Short" for the YouTube channel
