= Why Someday?

== Camping Log

November 11, 2022::
- Had 5th Wheel Installed on 2018 Ford F-150 at Ketelsen RV in Hiawath Iowa
- Bought 2022 Grand Design Reflection 295RL from Ketelsen RV in Hiawath Iowa

November 16, 2022::
- Took camper home to park in driveway
- Bumped back window with nose of camper and blew out back window!
- Got camper into the driveway and got truck wrapped with crash wrap
- Located new window at Ford of Murfreesboro, TN and booked a night at the Nashvill, I24 RV Park
- Scheduled glass install to be done at the campground.

November 18, 2022::
- Hit the road with snow on the ground. 
- First overnight at Harvest Host McDingerz Sports Bar & Grill in Eolia, MO
-- Found that our batteries were near dead and we had no hookups at this host (known ahead of time but not fully understood).
-- Ran to Lowe's and Home Depot to find a generator. Had to take what they had. 
-- Ran generator all night.
-- Found it to be too big for the back of our truck while the camper was hitched so had to go and return it to Home Depot. 
